<a href="https://colab.research.google.com/github/y-u-eun/python/blob/main/matrixEx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [107]:
# 2025.03.27
import numpy as np

while(True) :

  try :
      m = int(input('행의 크기를 입력하세요.'))

      if m <= 0 :
        print('0 또는 음수 입니다. 양수인 정수를 입력해주세요')
      else :
        break

  except ValueError :
      print('정수가 아닙니다.\n')

while(True) :

  try :
      n = int(input('열의 크기를 입력하세요.'))

      if n <= 0 :
        print('0 또는 음수 입니다. 양수인 정수를 입력해주세요')
      else :
        break

  except ValueError :
      print('정수가 아닙니다.\n')

lst = []

for j in range (0, m) :
  for i in range (0, n) :
    lst.append(j + i + 1)

arr = np.array(lst).reshape(m, n)

print(arr, type(arr))



행의 크기를 입력하세요.0
0 또는 음수 입니다. 양수인 정수를 입력해주세요
행의 크기를 입력하세요.-3
0 또는 음수 입니다. 양수인 정수를 입력해주세요
행의 크기를 입력하세요.61.25
정수가 아닙니다.

행의 크기를 입력하세요.-657.23
정수가 아닙니다.

행의 크기를 입력하세요.4
열의 크기를 입력하세요.0
0 또는 음수 입니다. 양수인 정수를 입력해주세요
열의 크기를 입력하세요.-4
0 또는 음수 입니다. 양수인 정수를 입력해주세요
열의 크기를 입력하세요.45.32
정수가 아닙니다.

열의 크기를 입력하세요.-653.2
정수가 아닙니다.

열의 크기를 입력하세요.5
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]] <class 'numpy.ndarray'>
